name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 85.215.131.239 >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
      
      - name: Deploy to VPS
        run: |
         echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
         chmod 600 private_key
         ssh -o StrictHostKeyChecking=no -i private_key root@85.215.131.239 'cd /home/sites/flepourtous && \
         echo "Début de l installation des dépendances" && \
         npm config set cache /home/sites/flepourtous/.npm-cache --global && \
         
         # Ajout du cache npm
         if [ ! -d ~/.npm ]; then
           mkdir -p ~/.npm
         fi
         npm ci --cache /home/sites/flepourtous/.npm-cache && \
         
         echo "Installation des dépendances terminée" && \
         echo "Début de la construction" && \
         npm run build && \
         echo "Construction terminée" && \
         pm2 restart your-app-name'
